---
title: "R Notebook"
output: html_notebook
---
```{r}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(sf)
library(tidygraph)
library(ggraph)
library(jsonlite)
theme_set(theme_bw())
sf_use_s2(FALSE)
```

```{r}
read_fun <- function(x) {
  read_sf(x) %>%
    st_cast("POLYGON") %>%
    mutate(
      path = str_remove(basename(x), "\\.geojson"),
      timepoint = as.integer(str_match(path, "[0-9]+")),
      layer_id = row_number()
    ) %>%
    select(-path, -lyr.1)
}

build_edges <- function(polygons) {
  times <- unique(polygons$timepoint)
  edges <- list()
  k <- 1
  
  for (i in seq_along(times)) {
    if (i == 1) next
    p1 <- filter(polygons, timepoint %in% times[i - 1])
    p2 <- filter(polygons, timepoint %in% times[i])
    intersections <- st_intersects(p1, p2)
    ix <- map_lgl(intersections, ~ !is_empty(.))
    
    for (i in which(ix)) {
      for (j in intersections[[i]]) {
        edges[[k]] <- data.frame(source = p1$id[i], target = p2$id[j])
        k <- k + 1
      }
    }
    
  }
 
  print(edges) 
  bind_rows(edges)
}

```

```{r}
paths <- list.files("../../data/shps/", "*.geojson", full = T)
lakes <- map_dfr(paths, read_fun) %>%
  arrange(timepoint) %>%
  mutate(id = row_number())
edges <- build_edges(lakes)
```

```{r}
plot(lakes %>% filter(id %in% c(edges$source, edges$target)) %>% pull(geometry))
```

```{r}
lakes_df <- lakes %>%
  as.data.frame() %>%
  select(-geometry) # keep lat / lon?
G <- tbl_graph(lakes_df, edges)
```

```{r}
ggraph(G %>% filter(id > 1000)) +
  geom_edge_link() +
  geom_node_point()
```

```{r}
write_sf(lakes, "../../data/shps/nodes.geojson")
G %>%
  activate(edges) %>%
  as.data.frame() %>%
  write_json("../../data/shps/edges.json")
```

